### ISSUE TITLE
Incorrect relayer address

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#30]
Consider the case of sending Eth from Ethereum to Aurora.

Here the `FtTransferMessageData` which we going to send to AuroraEngine is created: https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/deposit_event.rs#L166

https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/deposit_event.rs#L95

`account_id` in that context is NearEVM address (`aurora` or something like that). And we save this address to the `relayer` field. 

After that inside `aurora-engine` we transfer to that `relayer` the `fee`: https://github.com/aurora-is-near/aurora-engine/blob/feat/split-eth-connector/engine/src/connector.rs#L146

Are you sure this is the correct logic?

**Comment by mrLSD** [comment]
`aurora-eth-connector` contract relevant only to new version of `engine`: https://github.com/aurora-is-near/aurora-engine/pull/607

And in the new logic, we do not transfer any `fee` to `relayer`. And we can't change `FtTransferMessageData` because we should have the same public interface as the previous one.

And previously (before changes and removing relayer fee), the logic that you described was correct.

**Comment by olga24912** [comment]
The relayer doesn't get any fee, only the `aurora` account does.
