### ISSUE TITLE
Free account registration

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#33]
Usually, before using Fungible Tokens in Near the new user should register by transferring some storage deposit: https://docs.near.org/develop/relevant-contracts/ft#registering-a-user

However, in the current realization, some new users can be registered for free without storage_deposit. For example here: https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L223 or here https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L563

Moreover, we implement all standard FungiableTokens interfaces, including `storage_unregister` https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L434

which transfer `self.storage_balance_bounds().min.0 + 1` back to the user. So, he can get back the deposit that he never provided.

storage_balance_bounds().min.0 is a standard function that we don't change

**Comment by mrLSD** [comment]
We used standard storage_unregister or storage_withdraw.

1. storage_withdraw always panics
2. storage_unregister:
```
    fn internal_storage_unregister(
        &mut self,
        sender_id: AccountId,
        force: Option<bool>,
    ) -> Option<(AccountId, Balance)> {
        assert_one_yocto();
        let account_id = sender_id;
        let force = force.unwrap_or(false);
        if let Some(balance) = self.ft.accounts.get(&account_id) {
            if balance == 0 || force {
                self.ft.accounts.remove(&account_id);
                self.ft.total_supply -= balance;
                Promise::new(account_id.clone()).transfer(self.storage_balance_bounds().min.0 + 1);
                Some((account_id, balance))
            } else {
                env::panic_str(
                    "Can't unregister the account with the positive balance without force",
                )
            }
        } else {
            crate::log!("The account {} is not registered", &account_id);
            None
        }
    }
```
2.1. If `balance == 0` - just return attached deposit 1 yocto
2.2 if `forse` - same logic

What `register_account_if_not_exists` do? Because we used standard NEP-141 implementation, and actually `ft_transfer` - inside that method we `insert account`, and the standard function does not check storage_balance. But we need to count all available accounts. So that function pre-init account definitely will be created and increment counter. So it's all around standard NEP-141 methods.

**Comment by olga24912** [comment]
I see, the ft created without constructor, and the `account_storage_usage` set as zero. So it is consistent, and `storage_deposit` cost 0 Near tokens

https://github.com/aurora-is-near/aurora-eth-connector/blob/master/eth-connector/src/lib.rs#L189

https://docs.rs/near-contract-standards/latest/src/near_contract_standards/fungible_token/storage_impl.rs.html#100
