### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by olga24912** [aurora-is-near/aurora-eth-connector#35]
It would be very useful to indicate in the documentation that this contract is the implementation of Eth as a FT token on Near. Mentioning that this contract is specifically for Eth, and not for some abstract token, makes it much easier to understand the contract itself.

It would also be useful to add a link to the pair contract on the Ethereum side https://github.com/aurora-is-near/eth-connector

**Comment by mrLSD** [comment]
@olga24912 it doesn't true, because any user can use Aurora Engine, and the basic token can be not only Eth, but any other token depending on customer needs.

Eth-Conenctor itself means, that it can connect any Ethereum-compatible contract based on `aurora-engine` contract to use NEP-141 logic.

About the link to the contract. The end customer can use any solidity contract. The link that uses propose mainly related to Aurora products. But usage is not restricted only by Aurora itself.

**Comment by olga24912** [comment]
We can write it explicitly. That  it is just an example of a pair contract, but it can be some other contracts as well. Even the example can help to understand this contract.
